
import { Property } from './types';

export const MOCK_PROPERTIES: Property[] = [
  {
    id: '1',
    title: 'Casa Contemporânea nos Jardins',
    type: 'Casa',
    operation: 'Venda',
    price: 4500000,
    condoPrice: 0,
    iptuPrice: 1500,
    city: 'São Paulo',
    neighborhood: 'Jardins',
    street: 'Rua Estados Unidos',
    description: 'Casa espetacular com projeto arquitetônico premiado. Amplo jardim, piscina aquecida e acabamentos em mármore travertino.',
    bedrooms: 4,
    bathrooms: 5,
    area: 450,
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: '2',
    title: 'Apartamento Loft Industrial',
    type: 'Apartamento',
    operation: 'Aluguel',
    price: 8500,
    condoPrice: 1200,
    iptuPrice: 350,
    city: 'São Paulo',
    neighborhood: 'Vila Madalena',
    street: 'Rua Harmonia',
    description: 'Loft estilo industrial com pé direito duplo, grandes janelas e vista livre. Prédio com lazer completo e coworking.',
    bedrooms: 1,
    bathrooms: 2,
    area: 95,
    imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: '3',
    title: 'Cobertura Duplex Barra',
    type: 'Apartamento',
    operation: 'Venda',
    price: 2800000,
    condoPrice: 2500,
    iptuPrice: 800,
    city: 'Rio de Janeiro',
    neighborhood: 'Barra da Tijuca',
    street: 'Avenida Lúcio Costa',
    description: 'Cobertura duplex frente mar, sol da manhã, varanda gourmet e piscina privativa. Condomínio resort.',
    bedrooms: 3,
    bathrooms: 4,
    area: 220,
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: '4',
    title: 'Casa de Vila Charme',
    type: 'Casa',
    operation: 'Venda',
    price: 1200000,
    condoPrice: 150,
    iptuPrice: 200,
    city: 'Curitiba',
    neighborhood: 'Batel',
    street: 'Rua Comendador Araújo',
    description: 'Casa de vila totalmente reformada, muito silenciosa e segura. Próxima aos melhores restaurantes da cidade.',
    bedrooms: 2,
    bathrooms: 2,
    area: 120,
    imageUrl: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: '5',
    title: 'Sala Comercial Moderna',
    type: 'Comercial',
    operation: 'Aluguel',
    price: 3500,
    condoPrice: 800,
    iptuPrice: 120,
    city: 'Belo Horizonte',
    neighborhood: 'Savassi',
    street: 'Avenida do Contorno',
    description: 'Sala comercial pronta para uso, com ar condicionado central, piso elevado e recepção compartilhada.',
    bedrooms: 0,
    bathrooms: 1,
    area: 45,
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: '6',
    title: 'Terreno em Condomínio Fechado',
    type: 'Terreno',
    operation: 'Venda',
    price: 750000,
    condoPrice: 400,
    iptuPrice: 100,
    city: 'São Paulo',
    neighborhood: 'Centro',
    street: 'Condomínio Reserva da Mata',
    description: 'Lote plano em condomínio de alto padrão, pronto para construir. Área de lazer completa e segurança 24h.',
    bedrooms: 0,
    bathrooms: 0,
    area: 1000,
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800'
  }
];
